#ifndef CONSTANTS_H
#define CONSTANTS_H

// UI
#define CIRCLES_OUTLINE_THICKNESS 2.f
#define SCORE_TEXT_POSITION {10, 10}
#define TIMER_TEXT_POSITION {10, 50}
#define STATS_TEXT_SIZE 30
#define GAME_OVER_TEXT_SIZE 50

// LOGIC
#define START_SCORE 0
#define CIRCLES_COUNT 5
#define CIRCLE_RADIUS 30.f
#define TIME_FINE 1.0f
#define START_TIME 30.0f
#define FIND_FREE_POS_ATTEMPTS 100
#define SPEED_DIST_MIN 150.f
#define SPEED_DIST_MAX 300.f
#define ANGLE_DIST_MIN 0.f
#define ANGLE_DIST_MAX 6.28318f  // 2 * pi

// WINDOW
#define WINDOW_SIZE {800, 800}
#define WINDOW_TITLE "OSU HOME EDITION"

#endif